### ISSUE TITLE
Which implementation of pbkdf2 is used to match pw?

### ISSUE THREAD

**Issue by 7wonders** [emqtt/emq-auth-mysql#11]
Just wondering which is used so I can ensure the same method is used inserting passwords via python.

**Comment by 51systems** [comment]
We use this code to generate the password hash:
```python
def hash(password: str, salt: str) -> str:
    h = hashlib.sha256()

    h.update(password.encode('utf-8'))
    h.update(salt.encode('utf-8'))
    return h.hexdigest()
```

**Comment by emqplus** [comment]
Support the pbkdf2 password hash in 2.1.0-beta.2 release. PR: https://github.com/emqtt/emq-auth-mysql/pull/32
