### ISSUE TITLE
How to integrate with spring security?

### ISSUE THREAD

**Issue by samsong8610** [emqtt/emq-auth-mysql#12]
I use spring security to authenticate/authorization my web application, and I want to integrate the auth of emqtt.

In spring security, I use [BCryptPasswordEncoder](http://docs.spring.io/spring-security/site/docs/3.1.x/apidocs/org/springframework/security/crypto/bcrypt/BCryptPasswordEncoder.html) to encrypt the password with salt. The hashed password is like `$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.`, in which `$2a` is the fixed prefix for BCrypt method, `$10` is the salt length, `EblZqNptyY` is the salt and the last part `vcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.` is the hashed password.

Does emqttd_plugin_mysql support BCrypt hash function? And we must select password and salt in separate columns now. Is it possible to let the plugin to retrieve the salt from hashed password string?

This is a [spring security example](http://www.mkyong.com/spring-security/spring-security-password-hashing-example/) , for reference.
Thanks in advance.

**Comment by erylee** [comment]
Hi @samsong8610, I will check if we could support BCrypt hash.

**Comment by huangdan** [comment]
hi @samsong8610 
This feature has been release in 2.2-beta.2 official version
