### ISSUE TITLE
multiple topic filter support

### ISSUE THREAD

**Issue by karlvlam** [emqtt/emq-auth-mysql#5]
Thanks for this great project!

Does this plugin support filtering of multiple topics? If so, what should the setting be?

**Comment by erylee** [comment]
@karlvlam, resolved?

**Comment by karlvlam** [comment]
@erylee I think adding more rules for different topics should work (didn't tested yet...) Thank you for this great project Orz

**Comment by klausenbusk** [comment]
How was this implemented? Can a the topic column contain multiple filters, or do a I need to duplicate the row for every topic filter?

I tried separating two filters with `,` (`foo,bar`), but that doesn't seems to work..

**Comment by huangdan** [comment]
hi, @karlvlam 
you need to duplicate the row for every topic filter.
