### ISSUE TITLE
Cannot connect to MySQL 5.7

### ISSUE THREAD

**Issue by c00700702** [emqtt/emq-auth-mysql#62]

**Comment by huangdan** [comment]
![qq20170629-0](https://user-images.githubusercontent.com/970300/27678390-9f9b3dc8-5ce7-11e7-8a67-bb3f1e035ff2.png)

**Comment by codecafe-xls** [comment]
我也遇到同样的问题

**Comment by xtf1** [comment]
exactly the same as huangdan here.
database mariadb 10.3
switched server between 127.0.0.1 and localhost, same.
credentials are correct

**Comment by emqplus** [comment]
@HJianBo Please reproduce the issue with MySQL 5.7 and submit a PR to the Erlang MySQL driver project: https://github.com/mysql-otp/mysql-otp

**Comment by HJianBo** [comment]
I have tested this on MySQL5.7 and EMQ2.3, but can't reproduce this issue.

**Comment by emqplus** [comment]
@c00700702 @xtf1 Fixed the issue in 2.3.2 release.
