### ISSUE TITLE
Connnection refused: bad user name or password

### ISSUE THREAD

**Issue by yyguo1986** [emqtt/emq-auth-mysql#69]
I followed README.md to config and load this plugin. And inserted one user with name 'user' and password '123456' into mqtt_user table, but the connection was refused with errror 'bad user name or password' when testing.  Can anyone help?

_INSERT INTO mqtt_user (id, username, password, salt, is_superuser, created) 
VALUES
    (1,'user','123456','123456',True,'2016-10-26 10:00:00');_

_>mosquitto_sub -u user -P 123456  -d -i localmos -t #
Client localmos sending CONNECT
Client localmos received CONNACK
Connection Refused: bad user name or password._

**Comment by HJianBo** [comment]
@yyguo1986 
I guess you should set the hash method for password  to following line:
```
auth.mysql.password_hash = plain
```
Reload this plugin, try again!

**Comment by yyguo1986** [comment]
Yeah, it works. Thanks so much.

**Comment by yyguo1986** [comment]
Sorry, one more question:
After any update of conf file, currently it just works when restarting emqttd, not reloading this plugin. Why?

**Comment by HJianBo** [comment]
Yes, you are right! when you modified any `etc/*.conf` files, it just works when restarting emqttd! 

It's my mistake. sorry

**Comment by yyguo1986** [comment]
Thanks.
